# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
