# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-23 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170623_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='邮箱'),
        ),
    ]
