# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-23 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='salt'),
        ),
    ]
