# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-25 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_user_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
